on: push
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "importing all the document"
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        name: "installing the node.js with version 14"
      - run: .travis/affects.sh docs/ .travis || exit 0
        if: ${{ github.event_name == ('push' || 'pull_request')}} && ${{github.ref == 'master'}}
        name: "Build Docs"
      - run: |
         cd docs/
         source .travis/before_install.sh
         npm ci
        env:
          VERCEL_TOKEN: 3NFKE4wq2daxKnOrqgR7mGTH
           #repo-token: ${{ secrets.VERCEL_TOKEN }}
      - run: source .travis/script.sh

        name: "changing the directory to /docs"
#       - run: >
#          cd docs/
#          source .travis/script.sh
#         name: "running the .travis/script.sh"
