name: node_js

on:
  push:
    branches:  [master]
  pull_request:
    branches:  [master]
# env:
#    notification :
#                email: false

  
jobs :
  build :
    name : mybuilddemo
    runs-on: Ubuntu-18.04 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js node
        uses: actions/setup-node@v2
        with:
          node-version : 'node'

      - name: "Build Docs"
        if: ${{ github.event_name == 'push' && 'pull_request'&& github.ref == 'refs/heads/master'}}
#       - name: "Build Docs"
        run : |
          .travis -- affects.sh -- docs -- .travis || travis_terminate 0 
          cd docs/
          source .travis/before_install.sh
          npm ci
          source .travis/script.sh
#       - name : script
#         run : |
             #    || travis_terminate 0 

