name: node_js
on:
   push:
     branches: [master]
   pull: 
     branches: [master]
jobs:
   build: 
      runs-on: bionic
   - name: Build Docs
   if: type IN (push, pull_request) AND branch = master
   - name: Checkout repo
     uses: actions/checkout@v2
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v2
     with:
       node-version: lts/*
   - name: before_install
     run: .travis/affects.sh docs/ .travis || travis_terminate 0
     run: cd docs/
     run: source .travis/before_install.sh
     run: source .travis/script.sh
     
   
